name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Run flutter pub get
      - name: Get Flutter Dependencies
        run: flutter pub get

      # Ensure iOS deployment target is set to 14.0
      - name: Set iOS Deployment Target
        run: |
          echo "Setting iOS Deployment Target to 14.0"
          if grep -q "platform :ios" ios/Podfile; then
            sed -i '' 's/platform :ios.*/platform :ios, '\''14.0'\''/' ios/Podfile
          else
            echo "platform :ios, '14.0'" >> ios/Podfile
          fi

      # Update CocoaPods repo and install dependencies
      - name: Install CocoaPods
        run: |
          cd ios
          pod repo update
          pod install

      # Build the iOS release version without code signing
      - name: Build iOS Release
        run: flutter build ios --release --no-codesign

      # Prepare the IPA for export
      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r FlutterIpaExport.ipa Payload

      # Upload the IPA to the release
      - name: Upload IPA to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"


