name: iOS-ipa-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      # Step 3: Install dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Step 4: Clean and configure iOS project
      - name: Prepare iOS project
        run: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace
          flutter pub get
          flutter build ios --no-codesign --config-only

      # Step 5: Update Podfile for iOS deployment target
      - name: Set iOS Deployment Target
        run: |
          if grep -q "platform :ios" ios/Podfile; then
            sed -i '' 's/platform :ios.*/platform :ios, '\''14.0'\''/' ios/Podfile
          else
            echo "platform :ios, '14.0'" >> ios/Podfile
          fi

      # Step 6: Install CocoaPods dependencies
      - name: Install CocoaPods
        run: |
          cd ios
          pod repo update
          pod install

      # Step 7: Build the IPA
      - name: Build IPA
        env:
          CI: true
        run: flutter build ios --release --no-codesign

      # Step 8: Package the IPA
      - name: Create IPA Package
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r FlutterIpaExport.ipa Payload

      # Step 9: Upload the IPA as an artifact
      - name: Upload IPA to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FlutterIpaExport
          path: build/ios/iphoneos/FlutterIpaExport.ipa

