name: iOS-ipa-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Clean and Reset CocoaPods
      run: |
        flutter clean
        rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace
        cd ios && pod cache clean --all

    - name: Update iOS Deployment Target in Podfile
      run: |
        if grep -q "platform :ios" ios/Podfile; then
          sed -i '' 's/platform :ios.*/platform :ios, '\''14.0'\''/' ios/Podfile
        else
          echo "platform :ios, '14.0'" >> ios/Podfile
        fi

    - name: Update Deployment Target in Xcode Project
      run: |
        sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]\+\.[0-9]\+/IPHONEOS_DEPLOYMENT_TARGET = 14.0/' ios/Runner.xcodeproj/project.pbxproj

    - name: Install Dependencies
      run: flutter pub get

    - name: Generate iOS Build Config
      run: flutter build ios --no-codesign --config-only

    - name: Install CocoaPods Dependencies
      run: |
        cd ios
        pod repo update
        pod install

    - name: Build iOS App
      run: flutter build ios --release --no-codesign

