name: iOS-ipa-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        architecture: x64

    - name: Clean iOS Build
      run: |
        flutter clean
        rm -rf ios/Podfile ios/Podfile.lock ios/Pods ios/Runner.xcworkspace

    - name: Install Flutter Dependencies
      run: flutter pub get

    - name: Ensure Podfile Configuration
      run: |
        if [ ! -f ios/Podfile ]; then
          echo "
          platform :ios, '14.0'

          target 'Runner' do
            use_frameworks!
            use_modular_headers!
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end
          " > ios/Podfile
        fi

    - name: Configure iOS Build
      run: flutter build ios --no-codesign --config-only

    - name: Update Deployment Target in Xcode Project
      run: |
        sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]\+\.[0-9]\+/IPHONEOS_DEPLOYMENT_TARGET = 14.0/' ios/Runner.xcodeproj/project.pbxproj

    - name: Install CocoaPods Dependencies
      run: |
        cd ios
        pod repo update
        pod install

    - name: Build iOS App
      run: flutter build ios --release --no-codesign


